In [65]:
from pylab import*
from matplotlib import*
from scipy import*

In [66]:
def cofactor(A,temp,p,q,n):
    i=0
    j=0
    for row in range (n):
        for col in range (n):
            if row!=p and col!=q:
                temp[i,j]=A[row,col]
                j=j+1
                if j==n-1:
                    j=0
                    i=i+1

    return temp

In [67]:
def determinant (A,n):
    D=0
    if n==1:
        return A[0,0];
    temp=np.zeros((n,n));
    sign=1
    for f in range (n):
        temp=cofactor(A,temp,0,f,n)
        scer=determinant(temp,n-1)
        D += sign*A[0,f]*scer
        sign= -sign
    return D

In [68]:
def adjunt(A,adj):
    N=len(A)
    if N==1:
        adj[0,0]=1
        return
    sign=1,
    temp=np.zeros((N,N))
    for i in range (N):
        for j in range (N):
            temp=cofactor(A,temp,i,j,N)
            sign=(-1)**(i+j)
            fuck=determinant(temp, N-1)
            adj[j,i]=(sign)*(fuck)
    return adj

In [69]:
def inverse(A ,inverse):
    det= determinant(A,N)
    if det==0:
        return False 
    adj= np.zeros((N,N))
    adj=adjunt(A,adj);
    for i in range (N):
        for j in range (N):
            inverse[i,j]= adj[i,j]/det
    return inv

In [70]:
A = np.array([[1,2,3],[2,5,3],[1,0,8]])#ingrese matriz n por n

In [71]:
N=3 # valor de n de su matriz
adj= np.zeros((N,N))
inv= np.zeros((N,N))
#if (inverse(A,inv)):
    #print(inv)
inv=inverse(A,inv)
print (inv)

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]
